### ISSUE TITLE
How long geofence will monitor?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [aritchie/geofences#12]
How long geofence will monitor? (1 day, 1 month, forever or one time trigged)
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP
 - [x] .NET Standard

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Until you stop monitoring it.  Please take a look through the code yourself in the future.  It isn’t that big

**Comment by nguyenthanhliemfc** [comment]
Thank you!
