### ISSUE TITLE
Can not start Android Project after install?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [aritchie/geofences#13]
I get this error after install package, please help. Thank you!

**This package incompatible with Xam.Plugin.Geolocator and Plugin.Permission newest version**

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Plugin.Geolocator.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Plugin.Geolocator.Abstractions.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	MyApp.Android			

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [x] .NET Standard

## Version of OS(s) listed above with issue

Android all version
## Version of Library

2.0
## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Clean bin/obj - uninstall/reinstall all versions of the library.  This is a standard xamarin/VS problem.  Nothing to do with this library.

**Comment by nguyenthanhliemfc** [comment]
I tried!
I must downgrade that 2 plugin and it work fine!
Thank!

**Comment by IsmaelMendonca** [comment]
That's happening for me too. Getting the last version of plugins permissions and geolocator creates this issue.

But in my case downgrade is not a good option, there is something that could be done about it @aritchie?
