### ISSUE TITLE
How to run in background?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [aritchie/geofences#14]
I use "Started Service" to run in Background. Which code I must put in StartCommand method? Thank you!
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [x] .NET Standard

## Version of Library
2

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Use a sticky service if you want to keep it running indefinitely

**Comment by nguyenthanhliemfc** [comment]
Sorry for noob question!
I Sticky is final row of code in StartCommand method. Which code above, please give me some row of sample! Thank you!

**Comment by aritchie** [comment]
No offense, but do some googling.  I don't have an example readily available.  I take issues and feature requests here, please don't treat this as general support.
