### ISSUE TITLE
Please create a full sample run in background for Xamarin.Forms?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [aritchie/geofences#15]
Thank you for your plugin!
It's help me easy when create a geofence. But main mission of geofence is running in background.
If you have free time, please create a full sample Geofence run in Background for Xamarin.Forms (Android, iOS and UWP).
Thank a lot!

**Comment by aritchie** [comment]
listen man, I've tried to be polite.  I provide the code.  You use it at your own risk.  Background does work, you just need a sticky service to keep everything alive.

**Comment by nguyenthanhliemfc** [comment]
Thank you for polite.
I very hate when you close after one reply. You busy or you don't want support user. Please do not create anything when you don't want support user!

**Comment by aritchie** [comment]
I can do whatever I want with my code.  I was polite and you reply with a rude comment because I don't hold your hand through everything.  I can do whatever I like with my time and my code.

You are not welcome back.

**Comment by jd-alexander** [comment]
@aritchie thanks for such an amazing library and contribution and you sure can do whatever you want with your time. It's remarks like these that make open source toxic when people come demanding fixes, changes and support with no understanding at all.
