### ISSUE TITLE
no notifications when app is in background

### ISSUE THREAD

**Issue by NerPit** [aritchie/geofences#16]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [] .NET Standard

## Version of Library
2.0.0

## Expected Behaviour
when app is in background or closed i want to receive notifications about enter or exit an area

## Actual Behavior
it doesen't happen

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please install a sticky service into your app.  I don’t do this intentionally
