### ISSUE TITLE
Is there a timeout?

### ISSUE THREAD

**Issue by erportico** [aritchie/geofences#2]
HI, I'm using your component in one of my app. The component is working well. I noticed a glitch: after a short while (half an hour?) the component don't fire any events. What kind of problem can it be?
Thanks in advance.

**Comment by aritchie** [comment]
You need to give me context.  Platform? Code? Exception?

**Comment by erportico** [comment]
Thanks for your reply. I'm developing an app for Android.

        /// <summary>
        /// Sets the places.
        /// </summary>
        private void SetPlaces() {
            geofences.RegionStatusChanged += Geofences_RegionStatusChanged;
            geofences.StopAllMonitoring();
            
            List<Place> places = repo.GetPlaces();
            foreach (Place place in places) {
                try {
                    int regions = geofences.MonitoredRegions.Where(r => r.Identifier == place.Name.Trim()).Count();
                    if (regions == 0) {
                        geofences.StartMonitoring(new GeofenceRegion {
                            Identifier = place.Name.Trim(),
                            Radius = Distance.FromMeters(100),
                            Center = new Acr.Geofencing.Position(place.Latitude, place.Longitude)
                        });
                    }
                }
                catch (Exception ex) {
                    Debug.WriteLine(ex.Message);
                    log.SendMessageToAzure("Geofences Error", ex.Message);
                }
            }
        }

        private async void Geofences_RegionStatusChanged(object sender, GeofenceStatusChangedEventArgs e) {
            if (e.Status == GeofenceStatus.Unknown) {
                log.SendMessageToAzure("Geofences place", "Unknown");
            }
            else {
                if (e.Status == GeofenceStatus.Entered) {
             }
                if (e.Status == GeofenceStatus.Exited) {
             }
            }
        }

**Comment by aritchie** [comment]
I don't actually do anything to keep things alive in the background (neither does Plugin.Geolocator) such as a sticky or boot service, so if your app is being put to sleep nothing will bring it back up.

Also, the geolocator is actually used under the hood for this plugin (not google play services), so if you shutdown GPS, you will shutdown the geofences as well.

**Comment by aritchie** [comment]
Any luck?
