### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by manumohant** [aritchie/geofences#4]
I'm unable to install because of too many dependencies 
1. JSON.net must be less than 10.0.1
2. xam.plugin.geolocator must be less than v4. 

Is there any work around for this? I don't want to downgrade any of the dependencies in my project

**Comment by aritchie** [comment]
You'll have to wait for the next version which will be netstandard if you don't want to change your dependency version.

**Comment by tsoreywashoecounty** [comment]
any update on when we can expect the next version?
