### ISSUE TITLE
Unit testing geofences

### ISSUE THREAD

**Issue by robintschroeder** [aritchie/geofences#5]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] .NET Standard
Everything works great ;-) 

## Version of OS(s) listed above with issue
n/a 
Actual library functionality works great - you are awesome! 👍 
I am having trouble writing viewmodel unit tests and attempting to mock out the geofencing plugin.

## Version of Library
2.0.0

## Expected Behaviour
It would be really great if my unit test mock would work. I don't expect that the library be updated in any way. I am thinking there is something I need to do to mock this up that I am not doing? I guess I just need guidance. If you already have the answer here somewhere, I apologize if I didn't see it.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
`System.NotSupportedException : [Plugin.Geofencing] No platform plugin found.  Did you install the nuget package in your app project as well?`

So, I definitely have the permissions, geolocator and geofencing plugins installed the unit test project, the platform projects and the core (which targets .Net Standard 1.3).
I typically use a pattern like James has described here: 
https://montemagno.com/unit-testing-plugins-for-xamarin/

`
//first an abstract like this:
public static class CrossGeofences
    {
        private static IGeofenceManager geofenceManager;

        public static IGeofenceManager Current
        {
            get
            {
                return geofenceManager ?? (geofenceManager = CrossGeofences.Current);
            }
            set
            {
                geofenceManager = value;
            }
        }
    }

//then a mock like this:
 public class MockGeofenceManager : IGeofenceManager
    {
        public event EventHandler<GeofenceStatusChangedEventArgs> RegionStatusChanged;

        public Distance DesiredAccuracy { get => new Distance() { TotalKilometers = 1D }; set => new Distance() { TotalKilometers = 1D }; }
        public IReadOnlyList<GeofenceRegion> MonitoredRegions => new List<GeofenceRegion>() { new GeofenceRegion("New", new Plugin.Geofencing.Position(0D, 0D), new Distance()) };

        public Task<GeofenceStatus> RequestState(GeofenceRegion region, CancellationToken? cancelToken = null)
        {
            return Task.FromResult(GeofenceStatus.Entered);
        }

        public void StartMonitoring(GeofenceRegion region)
        {
        }

        public void StopAllMonitoring()
        {
        }

        public void StopMonitoring(GeofenceRegion region)
        {
        }
    }

//then a test like this: 
 [Test]
        public async void VMInitTest()
        {
            Permissions.Instance = new MockPermissions();
            //middle of the ocean
            CrossGeolocator.Current = new MockGeolocatorPosition00();
            CrossGeofences.Current = new MockGeofenceManager();
            Connectivity.Instance = new MockConnectivityConnected();
            CheckInOutViewModel vm = new CheckInOutViewModel(new MockNavService(), new 
 MockAnalyticsService(), new MockDataService(), new MockLoggingService());

            await vm.Init(); //Getting a not Implemented exception right here on the CrossGeolocator plugin. not sure why.
            Assert.AreEqual(GeofenceStatus.Exited, vm.GeofenceStatus);
         }

//and in my viewmodel, I am clearing the Geofence like this 
            //clean up
            CrossGeofences.Current.StopAllMonitoring();
` 

I am wondering if I need to inject a mock of the geolocator plugin somewhere into the geofencing plugin somehow? 
Alternatively, I am thinking that I just need to put the plugin behind an interface and mock it from there to test my code. Basically, I am using the geofence in an application that only needs to log behavior during a certain time period and I want a unit test around that code.  
Seriously, **you wrote a really cool thing here** and I don't want to waste your time. if you know exactly what is going on here, then it would be great to know how to make this work, but this problem isn't a super high priority. Thank you!

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
The CrossGeofences already has a setter specifically so you can do things like this.

**Comment by robintschroeder** [comment]
Sweet! Works like a charm! 
So, for those following along: To fix: get rid of your abstract...

**Don't need this part:**
//first an abstract like this:
/*public static class CrossGeofences
{
private static IGeofenceManager geofenceManager;

    public static IGeofenceManager Current
    {
        get
        {
            return geofenceManager ?? (geofenceManager = CrossGeofences.Current);
        }
        set
        {
            geofenceManager = value;
        }
    }
}*/
