### ISSUE TITLE
iOS 11 Location Permissions

### ISSUE THREAD

**Issue by robintschroeder** [aritchie/geofences#6]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS

## Version of OS(s) listed above with issue
11+

## Version of Library
2.0

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
Suggesting that you might want to update the setup section that the this plugin requires iOS 11 "Location Always" permission rather than just the regular location services permission from iOS 10 and earlier. 
As a result, all three of these are required in info.plist:
```
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Your message</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>your message</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>your message</string>
```

James M's Permissions Plugin added support for this 9 days ago. 
https://www.nuget.org/packages/Plugin.Permissions 

If I have some time, I may send you a pull request to help make supporting the "'WhenInUse" Location Services permission.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by robintschroeder** [comment]
Did I mention this plugin great? ;-)

**Comment by aritchie** [comment]
I appreciate the offer.  This library doesn't directly call for permissions.  Android and uwp make use of the geolocation plugin which does this.
