### ISSUE TITLE
 System.ArgumentException: Region identifier 'My Region' is already in use on start monitoring,unable to run to change the identifier name 

### ISSUE THREAD

**Issue by sanjuktadas** [aritchie/geofences#8]
private void Button_Clicked(object sender, EventArgs e)
        {
           
            CrossGeofences.Current.StartMonitoring(new GeofenceRegion("My Region",new Position(17.43203, 78.40727),Distance.FromMeters(2)));
            //CrossGeofences.Current.StartMonitoring(new GeofenceRegion("MyHouse", center: new Position(17.43203, 78.40727), radius: Distance.FromMeters(2)));
            //CrossGeofences.Current.StartMonitoring(new GeofenceRegion(identifier:"test", center: new Position(17.43203, 78.40727), radius: Distance.FromMeters(2)));
            //method1();

        }
when i click the button its crashing with System.ArgumentException: Region identifier 'My Region' is already in use on start monitoring,unable to run to change the identifier name issue.

sending the code created by your document
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using Plugin.Geofencing;
using System.Diagnostics;

namespace Geofencing2
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            

        }

        private void Button_Clicked(object sender, EventArgs e)
        {
           
            CrossGeofences.Current.StartMonitoring(new GeofenceRegion("My Region",new Position(17.43203, 78.40727),Distance.FromMeters(2)));
            //CrossGeofences.Current.StartMonitoring(new GeofenceRegion("MyHouse", center: new Position(17.43203, 78.40727), radius: Distance.FromMeters(2)));
            //CrossGeofences.Current.StartMonitoring(new GeofenceRegion(identifier:"test", center: new Position(17.43203, 78.40727), radius: Distance.FromMeters(2)));
            //method1();

        }
        public void method1() {
            DisplayAlert("Alert", "Method1 called", "ok");
            CrossGeofences.Current.RegionStatusChanged += (sender, args) =>
            {
                var regionOutput = args.Region;
                var statusOutput = args.Status;
                //Debug.WriteLine(string.Format("1111111{0} - 22222222{1}", regionOutput, statusOutput));
                DisplayAlert("Alert", string.Format("1111111{0} - 22222222{1}", regionOutput, statusOutput),"ok");
            };
        }
       

    }
}

 Plz resolve this

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] .NET Standard

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please fill out the form and a reproducible case if you want help here

**Comment by aritchie** [comment]
There's no bug here.  You need to check in the MonitoredRegions for a geofence config with that existing name OR StopAllMonitoring should you want to start fresh.

"Plz resolve this" => also note that I'm not here as a repair man.  you are welcome to review the code yourself :)
