### ISSUE TITLE
Can't run android project after plugin installation

### ISSUE THREAD

**Issue by Cliffy786** [aritchie/geofences#9]
For some reason that I'm unaware of, I cannot seem to run my  android project after installing the plugin. Any assistance would be highly appreciated.

**Comment by aritchie** [comment]
I’m not sure how I can help.  You haven’t given me any details to work with.  A crash, log, some code, etc

**Comment by Cliffy786** [comment]
I sorted that issue out somehow, I installed the plugin in a different project order, that seemed to do the trick :) , thanks for the response and the interest shown though aritchie, much appreciated. Can't get the local notification working though, although I'm within the radius of the geofence, I'm not getting any notifications.

**Comment by aritchie** [comment]
Geofences only fire when there is a change.  You can use Task<GeofenceStatus> RequestState(GeofenceRegion region, CancellationToken? cancelToken = null); which will give you the current state.
